package org.curitis.mapper;

import org.curitis.to.Experience;

public interface ExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int insert(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int insertSelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    Experience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int updateByPrimaryKeySelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Experience record);
}