package org.curitis.mapper;

import org.curitis.to.QuestionAnswer;

public interface QuestionAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int insert(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int insertSelective(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    QuestionAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int updateByPrimaryKeySelective(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(QuestionAnswer record);
}