package org.curitis.to;

public class Experience {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.content
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.id
     *
     * @return the value of experience.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.id
     *
     * @param id the value for experience.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.content
     *
     * @return the value of experience.content
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.content
     *
     * @param content the value for experience.content
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}