package org.curitis.to;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.knowledge
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private String knowledge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type_id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question
     *
     * @return the value of question.question
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question
     *
     * @param question the value for question.question
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.knowledge
     *
     * @return the value of question.knowledge
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public String getKnowledge() {
        return knowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.knowledge
     *
     * @param knowledge the value for question.knowledge
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setKnowledge(String knowledge) {
        this.knowledge = knowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type_id
     *
     * @return the value of question.type_id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type_id
     *
     * @param typeId the value for question.type_id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}