package org.curitis.to;

public class QuestionAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.id
     *
     * @return the value of question_answer.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.id
     *
     * @param id the value for question_answer.id
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.answer
     *
     * @return the value of question_answer.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.answer
     *
     * @param answer the value for question_answer.answer
     *
     * @mbg.generated Fri Apr 05 16:51:11 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}